# general configuration
url: http://astraw38.github.io
baseurl: ''
name: 'Decodest'
description: "Python & Linux automated testing blog"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
gems:
 - jekyll-paginate
 - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
 - jekyll-feed # Create an Atom feed using the official Jekyll feed gem


# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:title/

sass:
  sass_dir: _scss

# Includes an icon in the footer for each username you enter
footer-links:
  github: astraw38
  rss: hi # just type anything here for a working RSS icon
  twitter: LuvlyOvipositor
